config/routes.rb
Rails.application.routes.draw do

  root 'frontend#index'
  get 'frontend/index'
  post 'frontend/search'
  get 'frontend/show/:id' => 'frontend#show', as: :show_book

  get 'frontend/advanced_search'
  post 'frontend/advanced_search'

  resources :types
  resources :categories
  resources :books

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def search
    @books = Book.search(params).includes(:category).includes(:type)
  end

  def advanced_search
    @search = Book.ransack(params[:q])
    @books = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

end

app/helpers/frontend_helper.rb
module FrontendHelper

  def link_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    id = "new_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-success btn-xs", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def predicate_conditions
    [:eq, :cont, :cont_any, :cont_all, :not_cont, :not_cont_any, :not_cont_all, :start, :start_any, :start_all, :not_start, :not_start_any, :not_start_all, :end, :end_any, :end_all, :not_end, :not_end_any, :not_end_all, :lt, :lteq, :gt, :gteq]
  end

end

app/views/frontend/_condition_fields.html.erb
<div class="field">

  <div class="row">
    <div class="col-lg-3">
      <%= f.attribute_fields do |a| %>
          <%= a.attribute_select({associations: [:category, :type]},{class: "form-control"}) %>
      <% end %>
    </div>
    <div class="col-lg-3">
      <%= f.predicate_select({only: predicate_conditions}, {class: 'form-control'}) %>
    </div>
    <div class="col-lg-4">
      <%= f.value_fields do |v| %>
          <%= v.text_field :value,{class: 'form-control'}  %>
      <% end %>
    </div>
    <div class="col-lg-2">
      <%= link_to "Remove".html_safe, '#', class: "remove_fields btn btn-warning btn-sm" %>
    </div>
  </div>
  <hr/>
</div>

app/views/frontend/advanced_search.html.erb
<h1>Advanced search</h1>
<hr/>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Search</h3>
  </div>
  <div class="panel-body">

    <%= search_form_for @search, url: frontend_advanced_search_path, method: :post do |f| %>

        <%= f.condition_fields do |c| %>
            <%= render "condition_fields", f: c %>
        <% end %>

        <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>

        <hr/>

        <div class="row">
          <div class="form-group">
            <div class="col-md-2">
              <%= f.label "Sort by book:", class: "control-label" %>
            </div>
            <%= f.sort_fields do |s| %>
                <div class="col-md-10">
                  <%= s.sort_select({}, {class: 'form-control', style: "width:40%; float:left; margin-right:30px;"}) %>
                </div>
            <% end %>
          </div>
        </div>

        <hr/>
        <div class="actions">
          <%= button_tag class: "btn btn-success form-control" do %>
              <i class='fa fa-search'></i> Search
          <% end %>
        </div>

    <% end %>
  </div>
</div>


<div class="alert alert-info" role="alert"> We've found <%= @books.size %> records matching your cryteria.</div>

<table class="table table-striped display codes">
  <thead>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Type</th>
    <th>Author</th>
    <th>Year</th>
    <th>Publisher</th>
    <th>ISBN</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, show_book_path(book) %></td>
        <td><%= book.category.title %></td>
        <td><%= book.type.title %></td>
        <td><%= book.author %></td>
        <td><%= date(book.year) %></td>
        <td><%= book.publisher %></td>
        <td><%= book.isbn %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<hr/>

<%= link_to "<i class='fa fa-home'></i> Back to home".html_safe, frontend_index_path, class: "btn btn-default" %>

app/views/frontend/index.html.erb
<h1>Find your favorite book!</h1>
<h2>We have currently <%= @books.size %> books in our database.</h2>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Search</h3>
  </div>
  <div class="panel-body">

    <%= form_tag frontend_search_path, method: :post, class: 'form-horizontal', role: 'form', id: 'basic_search_form' do %>

        <div class="alert alert-info" role="alert">Use this form to perform a simple search by category and type. Click <strong><%= link_to "HERE", frontend_advanced_search_path %></strong> if you want to try our advanced search.</div>

        <div class="form-group">
          <%= label_tag :category, nil, class: "col-lg-2 control-label" %>
          <div class="col-lg-10">
            <div class="row">
              <div class="col-lg-10">
                <%= text_field_tag :category, nil, class: 'form-control col-lg-6', required: true %>
              </div>
              <div class="col-lg-2">
                <%= label_tag nil, class: "radio-inline" do %>
                    <%= radio_button_tag :category_options, '&&', checked: true %> &&
                <% end %>
                <%= label_tag nil, class: "radio-inline" do %>
                    <%= radio_button_tag :category_options, '||' %> ||
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= label_tag :type, nil, class: "col-lg-2 control-label" %>
          <div class="col-lg-10">
            <div class="row">
              <div class="col-lg-10">
                <%= text_field_tag :type, nil, class: 'form-control col-lg-6', required: true %>
              </div>
              <div class="col-lg-2">
                <%= label_tag nil, class: "radio-inline" do %>
                    <%= radio_button_tag :type_options, '&&', checked: true %> &&
                <% end %>
                <%= label_tag nil, class: "radio-inline" do %>
                    <%= radio_button_tag :type_options, '||' %> ||
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-offset-2 col-lg-10">
            <%= button_tag(type: 'submit', class: "btn btn-success") { "Search".html_safe } %>
          </div>
        </div>

    <% end %>
  </div>
</div>

<div class="well">

  <h3>Debug for testing/search purposes</h3>
  <hr/>
  <h4>Available category titles</h4>
  <%= Category.all.collect(&:title) %>
  <h4>Available type titles</h4>
  <%= Type.all.collect(&:title) %>

</div>

app/views/frontend/search.html.erb
<h1>Search results
  <div class="btn-group pull-right">
    <%= link_to "<i class='fa fa-home'></i> Back to home".html_safe, frontend_index_path, class: "btn btn-default" %>
  </div>
</h1>
<div class="alert alert-info" role="alert"> We've found <%= @books.size %> records matching your cryteria. </div>

<table class="table table-striped display codes">
  <thead>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Type</th>
    <th>Author</th>
    <th>Year</th>
    <th>Publisher</th>
    <th>ISBN</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, show_book_path(book) %></td>
        <td><%= book.category.title %></td>
        <td><%= book.type.title %></td>
        <td><%= book.author %></td>
        <td><%= date(book.year) %></td>
        <td><%= book.publisher %></td>
        <td><%= book.isbn %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<hr/>

<%= link_to "<i class='fa fa-home'></i> Back to home".html_safe, frontend_index_path, class: "btn btn-default" %>

app/views/frontend/show.html.erb
<h1><%= @book.title %>
  <div class="btn-group pull-right">
    <%= link_to "<i class='fa fa-list'></i> Back to list".html_safe, 'javascript:history.go(-1);', class: "btn btn-default" %>
  </div>
</h1>
<hr/>

<div class="row">

  <div class="col-lg-5">
    <h3>Cover</h3>
    <%= image_tag "fake-cover.jpg", class: "img-thumbnail img-responsive" %>
  </div>
  <div class="col-lg-7">

    <h3>Details</h3>

    <ul class="list-group">
      <li class="list-group-item"><strong>Author:</strong> <%= @book.author %></li>
      <li class="list-group-item"><strong>Year:</strong> <%= date(@book.year) %></li>
      <li class="list-group-item"><strong>Publisher:</strong> <%= @book.publisher %></li>
      <li class="list-group-item"><strong>ISBN:</strong> <%= @book.isbn %></li>
    </ul>

    <h3>Book synopsis</h3>

    <div class="well">
      <%= @book.description %>
    </div>

    <h3>Download</h3>

    <% @book.files.each do |file| %>
       <%= download_button(file) %>
    <% end %>

    <% unless @book.files.any? %>
    <div class="alert alert-warning" role="alert"><strong>Sorry,</strong> no versions currently available for download.</div>
    <% end %>

  </div>

</div>

<hr/>
<%= link_to "<i class='fa fa-list'></i> Back to list".html_safe, 'javascript:history.go(-1);', class: "btn btn-default" %>