config/routes.rb
Rails.application.routes.draw do

  root 'frontend#index'
  get 'frontend/index'
  post 'frontend/search'
  get 'frontend/show/:id' => 'frontend#show', as: :show_book

  get 'frontend/advanced_search'
  post 'frontend/advanced_search'

  resources :types
  resources :categories
  resources :books

end

app/controllers/types_controller.rb
# == Schema Information
#
# Table name: types
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:title)
    end
end

app/helpers/types_helper.rb
# == Schema Information
#
# Table name: types
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module TypesHelper
end

app/views/types/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <%= form_for(@type, html: {class: 'form-horizontal', role: 'form'}) do |f| %>

        <%= errors_for(@type) %>

        <div class="form-group">
          <%= f.label :title, class: "control-label col-md-2" %>
          <div class="col-md-6">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>

        <div class="actions">
          <%= button_tag class: "btn btn-success form-control" do %>
              <i class='fa fa-check-square-o'></i> Confirm
          <% end %>
        </div>

    <% end %>

  </div>
</div>

app/views/types/edit.html.erb
<h1>Editing type
  <div class="btn-group pull-right">
    <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, types_path, class: "btn btn-default" %>
    <%= link_to "<i class='fa fa-fw fa-search'></i>".html_safe, @type, class: "btn btn-default" %>
  </div>
</h1>

<hr/>

<%= render 'form' %>

app/views/types/index.html.erb
<h1>Listing types
  <span class="pull-right"><%= link_to "<i class='fa fa-plus'></i>".html_safe, new_type_path, class: "btn btn-success" %></span>
</h1>
<hr/>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @types.each do |type| %>
      <tr>
        <td><%= type.title %></td>
        <td>
          <div class="button-group">
            <%= link_to "<i class='fa fa-fw fa-search'></i>".html_safe, type %>
            <%= link_to "<i class='fa fa-fw fa-edit'></i>".html_safe, edit_type_path(type) %>
            <%= link_to "<i class='fa fa-fw fa-trash-o'></i>".html_safe, type, method: :delete, data: {confirm: 'Are you sure?'} %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/types/new.html.erb
<h1>New type
  <span class="pull-right"><%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, types_path, class: "btn btn-default" %></span>
</h1>
<hr/>

<%= render 'form' %>

app/views/types/show.html.erb
<h1>type
  <div class="btn-group pull-right">
    <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, types_path, class: "btn btn-default" %>
    <%= link_to "<i class='fa fa-fw fa-edit'></i>".html_safe, edit_type_path(@type), class: "btn btn-default" %>
    <%= link_to "<i class='fa fa-plus'></i>".html_safe, new_type_path, class: 'btn btn-success' %>
  </div>
</h1>
<hr/>

<p>
  <strong>Title:</strong>
  <%= @type.title %>
</p>