config/routes.rb
Rails.application.routes.draw do

  root 'frontend#index'
  get 'frontend/index'
  post 'frontend/search'
  get 'frontend/show/:id' => 'frontend#show', as: :show_book

  get 'frontend/advanced_search'
  post 'frontend/advanced_search'

  resources :types
  resources :categories
  resources :books

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base

  # Validates the presence of required fields before proceed to record creation or update
  #
  # == Required fields:
  #
  #   - title
  #
  validates_presence_of :title

  # Associations
  #
  #
  has_many :books

  # Ransack gem searchable attributes for current model
  #
  #
  def self.ransackable_attributes(auth_object = nil)
    %w(title) + _ransackers.keys
  end

end

app/controllers/categories_controller.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <%= form_for(@category, html: {class: 'form-horizontal', role: 'form'}) do |f| %>

        <%= errors_for(@category) %>

        <div class="form-group">
          <%= f.label :title, class: "control-label col-md-2" %>
          <div class="col-md-6">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>

        <div class="actions">
          <%= button_tag class: "btn btn-success form-control" do %>
              <i class='fa fa-check-square-o'></i> Confirm
          <% end %>
        </div>

    <% end %>

  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing category
  <div class="btn-group pull-right">
    <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, categories_path, class: "btn btn-default" %>
    <%= link_to "<i class='fa fa-fw fa-search'></i>".html_safe, @category, class: "btn btn-default" %>
  </div>
</h1>

<hr/>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Listing categories
  <span class="pull-right"><%= link_to "<i class='fa fa-plus'></i>".html_safe, new_category_path, class: "btn btn-success" %></span>
</h1>
<hr/>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td>
          <div class="button-group">
            <%= link_to "<i class='fa fa-fw fa-search'></i>".html_safe, category %>
            <%= link_to "<i class='fa fa-fw fa-edit'></i>".html_safe, edit_category_path(category) %>
            <%= link_to "<i class='fa fa-fw fa-trash-o'></i>".html_safe, category, method: :delete, data: {confirm: 'Are you sure?'} %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New category
  <span class="pull-right"><%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, categories_path, class: "btn btn-default" %></span>
</h1>
<hr/>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1>category
  <div class="btn-group pull-right">
    <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, categories_path, class: "btn btn-default" %>
    <%= link_to "<i class='fa fa-fw fa-edit'></i>".html_safe, edit_category_path(@category), class: "btn btn-default" %>
    <%= link_to "<i class='fa fa-plus'></i>".html_safe, new_category_path, class: 'btn btn-success' %>
  </div>
</h1>
<hr/>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>