config/routes.rb
Rails.application.routes.draw do

  root 'frontend#index'
  get 'frontend/index'
  post 'frontend/search'
  get 'frontend/show/:id' => 'frontend#show', as: :show_book

  get 'frontend/advanced_search'
  post 'frontend/advanced_search'

  resources :types
  resources :categories
  resources :books

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(value)
    unless value.nil?
      @title = "#{value} | Alexandria"
    end
  end

  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: "panel panel-danger") do
        concat(content_tag(:div, class: "panel-heading") do
          concat(content_tag(:h4, class: "panel-title") do
            concat "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase.gsub('dtscmsadmin::','')} from being saved:"
          end)
        end)
        concat(content_tag(:div, class: "panel-body") do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end

  def date(date)
    date.strftime("%d-%m-%Y") rescue nil
  end

  def datetime(date)
    date.strftime("%d/%m/%Y at %I:%M%p") rescue nil
  end

end

app/views/application/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top ">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-book"></i> Alexandria</a>
    <% end %>

    <%= render 'navigation_links' %>

  </div>
</div>

app/views/application/_navigation_links.html.erb
<div class="navbar-collapse collapse navbar-responsive-collapse navbar-right">
  <ul class="nav navbar-nav">
    <li>
      <%= link_to frontend_advanced_search_path do %>
        <i class="fa fa-search"> Advanced search</i>
      <% end %>
    </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-cogs"></i> Admin <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Books", books_path %></li>
        <li><%= link_to "Categories", categories_path %></li>
        <li><%= link_to "Types", types_path %></li>
      </ul>
    </li>
  </ul>
</div>